using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Fangame.UI
{
    public class CommanderPanel : MonoBehaviour
    {
        [Header("UI Elements")]
        public TextMeshProUGUI commanderNameText;
        public TextMeshProUGUI commanderTitleText;
        public TextMeshProUGUI levelText;
        public TextMeshProUGUI tierText;
        public TextMeshProUGUI pvpScoreText;
        public Image portraitImage;
        public Slider xpSlider;
        public Button skillsButton;
        public TextMeshProUGUI skillPointsBadge;

        [Header("Stats")]
        public TextMeshProUGUI attackText;
        public TextMeshProUGUI defenseText;
        public TextMeshProUGUI leadershipText;

        public void Populate(CommanderData data)
        {
            commanderNameText.text = data.name;
            commanderTitleText.text = data.title;
            levelText.text = $"Lvl {data.level}";
            tierText.text = GetTierLabel(data.pvpScore);
            pvpScoreText.text = $"{data.pvpScore}/20.0";
            
            attackText.text = data.attack.ToString();
            defenseText.text = data.defense.ToString();
            leadershipText.text = data.leadership.ToString();

            xpSlider.maxValue = data.level * 1000;
            xpSlider.value = data.xp;

            // [TODO] Load dynamic portrait generated by AI
        }

        private string GetTierLabel(float score)
        {
            if (score >= 17) return "S+ TIER";
            if (score >= 15) return "S TIER";
            if (score >= 13) return "S- TIER";
            if (score >= 11) return "A TIER";
            if (score >= 9) return "B TIER";
            return "C-F TIER";
        }
    }

    [System.Serializable]
    public class CommanderData
    {
        public string name;
        public string title;
        public int level;
        public int xp;
        public float pvpScore;
        public int attack;
        public int defense;
        public int leadership;
        public int availableSkillPoints;
        public int respectLevel;
    }
}
